# Tyger stellar.toml

SEP 0001 specifies five sections you can add to your stellar.toml: 
Account Information, 
Issuer Documentation, 
Point of Contact Documentation, 
Currency Documentation,
Validator Information. 

Within those sections, some fields only apply to specialized tokens, but many apply to all tokens, and these guidelines will outline which fields are:

Required: all token issuers must include this information in their stellar.toml if they want to be listed on exchanges.

Suggested: any token issuer who wants their offering to stand out should complete these fields.

#   The endpoint which clients should query to resolve stellar addresses
#   for users on your domain.
FEDERATION_SERVER="https://api.stellar.org/federation"

# The endpoint used for the compliance protocol
AUTH_SERVER="https://api.stellar.org/auth"

# The signing key is used for the compliance protocol
#SIGNING_KEY="GBBHQ7H4V6RRORKYLHTCAWP6MOHNORRFJSDPXDFYDGJB2LPZUFPXUEW3"

# convenience mapping of common names to node IDs.
# You can use these common names in sections below instead of the less friendly nodeID.
# This is provided mainly to be compatible with the stellar-core.cfg
#NODE_NAMES=[
#"GD5DJQDDBKGAYNEAXU562HYGOOSYAEOO6AS53PZXBOZGCP5M2OPGMZV3  lab1",
#"GB6REF5GOGGSEHZ3L2YK6K4T4KX3YDMWHDCPMV7MZJDLHBDNZXEPRBGM  donovan",
#"GBGR22MRCIVW2UZHFXMY5UIBJGPYABPQXQ5GGMNCSUM2KHE3N6CNH6G5  nelisky1",
#"GDXWQCSKVYAJSUGR2HBYVFVR7NA7YWYSYK3XYKKFO553OQGOHAUP2PX2  jianing",
#"GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U  anchor"
#]

#   A list of accounts that are controlled by this domain.
#ACCOUNTS=[
#"$sdf_watcher1",
#"GAENZLGHJGJRCMX5VCHOLHQXU3EMCU5XWDNU4BGGJFNLI2EL354IVBK7"
#]

[DOCUMENTATION]
ORG_NAME="ACET"
ORG_DBA="Analytical Center of Excellence on Trafficking"
ORG_URL="https://acet-recover.com"
#ORG_LOGO="https://acet-recover.com/logo.jpg"
ORG_DESCRIPTION="The Analytical Center of Excellence on Trafficking (ACET, pronounced “asset”) helps stakeholders make sound and timely decisions that reduce trafficking, thereby saving time, money and lives."
ORG_PHYSICAL_ADDRESS="123 Sesame St., New York, NY, 12345" 
#ORG_PHYSICAL_ADDRESS_ATTESTATION=!"https://www.domain.com/address_attestation.jpg"
ORG_PHONE_NUMBER="1 (123)-456-7890"
ORG_PHONE_NUMBER_ATTESTATION="https://www.domain.com/phone_attestation.jpg"
#ORG_KEYBASE=!"accountname"
#ORG_TWITTER=!"orgtweet"
#ORG_GITHUB=!"orgcode"
ORG_OFFICIAL_EMAIL="admin@acet-recover.com"

[[PRINCIPALS]]
name="Daniel Swid"
email="daniel@generationblue.com"
twitter="@crypto_jane"
keybase="crypto_jane"
github="crypto_jane"
id_photo_hash="5g249e170f4f134b18ab3de069c5a13e5c3ef3ef90f3643afa15a1603c34cf38"
verification_photo_hash="693687f6abd594366a09cfe6b380e58f9023867a851cc9fa71f302ab4889e48"

#   Any validation public keys that are declared
#   to be used by this domain for validating ledgers and are
#   authorized signers for the domain.
OUR_VALIDATORS=[
"$sdf_watcher2",
"GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH"
]

# DESIRED_BASE_FEE (integer)
# This is what you would prefer the base fee to be. It is in stroops.
DESIRED_BASE_FEE=100

# DESIRED_MAX_TX_PER_LEDGER (integer)
# This is how many maximum transactions per ledger you would like to process.
DESIRED_MAX_TX_PER_LEDGER=400

#   List of IPs of known stellar-core's.
#   These are IP:port strings.
#   Port is optional.
#   By convention, IPs are listed from most to least trusted, if that information is known.
KNOWN_PEERS=[
"192.168.0.1",
"core-testnet1.stellar.org",
"core-testnet2.stellar.org:11290",
"2001:0db8:0100:f101:0210:a4ff:fee3:9566"
]

# list of history archives maintained by this domain
HISTORY=[
"http://history.stellar.org/prd/core-live/core_live_001/",
"http://history.stellar.org/prd/core-live/core_live_002/",
"http://history.stellar.org/prd/core-live/core_live_003/"
]

#   This section allows an anchor to declare currencies it currently issues.
#   Can be used by wallets and clients to trust anchors by domain name
[[CURRENCIES]]

# asset with meta info
[[CURRENCIES]]
code="TYGER"
issuer=!"GD5T6IPRNCKFOHQWT264YPKOZAWUMMZOLZBJ6BNQMUGPWGRLBK3U7ZNP"
status="live"
display_decimals=2
name="TYGER"
desc="A Tyger token is pegged to 100 square meters of core tiger habitat"
conditions="There will only ever be 10,000 GOAT tokens in existence. We will distribute the revenue share annually on Jan. 15th"
image="https://pbs.twimg.com/profile_images/666921221410439168/iriHah4f.jpg"

#   Potential quorum set of this domain's validators.
[QUORUM_SET]
VALIDATORS=[
"$self", "$lab1", "$nelisky1","$jianing",
"$eno","$donovan"
]

# optional extra information for humans
# Useful place for anchors to detail various policies and required info

###################################
# Required compliance fields:
#      name=<recipient name>
#      addr=<recipient address>
# Federation Format:  
#        <phone number>*anchor.com
#        Forwarding supported by sending to: forward*anchor.com
#           forward_type=bank_account
#           swift=<swift code of receiving bank>
#           acct=<recipient account number at receiving bank>
# Minimum Amount Forward: $2 USD
# Maximum Amount Forward: $10000 USD
